create table if not exists Userdata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) not null,
  first_name varchar(50) not null,
  last_name varchar(50) not null
);
