create table if not exists todo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT random_uuid(),
    title varchar(255) not null,
    description text,
    completed boolean not null default false
);
