create table if not exists City (
  city_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) not null
);

create table if not exists Person (
  person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(50) not null,
  last_name varchar(50) not null,
  email varchar(50) not null,
  city_id BIGINT,
  foreign key (city_id) references City(city_id)
);